[app]
app-secret-key=56n68oS2PiciB38DEImv

[detection]
# Umbral de confianza para considerar un animal como "conocido"
# Si la probabilidad máxima es menor que este valor, se considera "animal desconocido"
confidence_threshold=0.5
# Mensaje para animales desconocidos
unknown_animal_message=Animal Desconocido - No está en la base de datos